spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  application:
    name: backend
#  cloud:
#    config:
#      uri: http://${config.host:192.168.1.140}:${config.port:8888}

server:
  port: 80

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery/eureka/

management.security.enabled: false

security:
  oauth2:
    resource:
      id: backend
      user-info-uri: http://api-gateway/uaa/user  #用户信息的获取，异构系统要自己做，spring cloud系直接对接
      prefer-token-info: false

logging.level.org.springframework.security: DEBUG